#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Resume state. The values captured below are Vercel/DNS bookkeeping, not app
# config, so they go in a wizard-local file rather than the app's .env.
ENV_FILE="${ENV_FILE:-.scratch/marketing-app-split/.cutover.env}"

TEAM="gut8er-pro"
GH_ORG="gut8er-pro"
VERCEL_GH_INSTALL_ID="110446855"   # Vercel's GitHub App installation on the org
APP_PROJECT="gut8er-pro"           # existing Vercel project, linked to github gut8er-pro/core
SITE_PROJECT="website"             # new Vercel project for the Astro marketing site
SUPABASE_REF="cqgzckghgoyzijxgbncw"
SUPABASE_CALLBACK="https://${SUPABASE_REF}.supabase.co/auth/v1/callback"
APP_ORIGIN="https://app.gut8erpro.de"
MARKETING_ORIGIN="https://gut8erpro.de"
VERCEL_APEX_A="76.76.21.21"        # Vercel's documented apex A record

banner "Gut8erPRO — marketing/app split cutover"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Vercel — create the marketing site project"
say "The Astro site lives in its own repo. Link it to a new Vercel project so"
say "it redeploys on every push."
note "Verified already true, nothing to do for the app: ${APP_ORIGIN} exists,"
note "resolves to Vercel, and serves the '${APP_PROJECT}' project today."
say ""
warn "Do this FIRST — Vercel cannot see the repo until you do."
say "Vercel's GitHub App is installed on the org with 'only selected repositories',"
say "so a newly created repo is invisible to it until it is added. Only an"
say "Organization Owner can change this (the API refuses everyone else)."
open_url "https://github.com/organizations/${GH_ORG}/settings/installations/${VERCEL_GH_INSTALL_ID}"
step "Under 'Repository access', add ${GH_ORG}/website to the selected list. Save."
pause "Vercel granted access to the website repo?"
say ""
open_url "https://vercel.com/new/${TEAM}"
step "Import the ${GH_ORG}/website repository."
step "Project name: ${SITE_PROJECT}"
step "Framework preset: Astro (Vercel should detect this automatically)."
step "Leave the build command and output directory at their defaults."
step "Deploy, and wait for the first build to go green."
say ""
say "Optional — the site builds correctly without it, because the production"
say "fallback already points at ${APP_ORIGIN}:"
step "Settings → Environment Variables → add PUBLIC_APP_URL = ${APP_ORIGIN}"
pause "Marketing project created and deployed?"

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Vercel — attach the apex and www to the marketing site"
say "The apex currently points at a united-domains parking page, not at Vercel."
warn "Add the domains in Vercel FIRST, then change DNS (next stage). Vercel"
warn "shows you the exact records to use only after the domain is added."
open_url "https://vercel.com/${TEAM}/${SITE_PROJECT}/settings/domains"
step "Add domain: gut8erpro.de"
step "Add domain: www.gut8erpro.de"
step "For www, choose 'Redirect to gut8erpro.de' with status 308 (or 301)."
step "Leave both showing 'Invalid Configuration' for now — DNS comes next."
say ""
say "Copy down the two records Vercel displays on this screen. The apex is"
say "normally an A record to ${VERCEL_APEX_A}; the www CNAME target is"
say "project-specific, so copy it exactly rather than guessing."
ask VERCEL_WWW_CNAME "Paste the CNAME target Vercel shows for www:"
ask VERCEL_APEX_VALUE "Paste the A (or ALIAS) value Vercel shows for the apex:"
# Persist them: stage 3 prints these records back, and a Ctrl-C between the two
# stages would otherwise lose the project-specific CNAME target on re-run.
[[ -n "$VERCEL_WWW_CNAME" ]]  && write_env VERCEL_WWW_CNAME  "$VERCEL_WWW_CNAME"
[[ -n "$VERCEL_APEX_VALUE" ]] && write_env VERCEL_APEX_VALUE "$VERCEL_APEX_VALUE"
pause "Domains added in Vercel?"

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "united-domains — set the DNS records"
say "Your registrar is united-domains (nameservers ns.udag.net/.org/.de), so"
say "DNS is managed there, not on Vercel."
open_url "https://www.united-domains.de/login"
step "Open the DNS settings for gut8erpro.de."
say ""
say "  Set the apex (@):   A      ->  ${VERCEL_APEX_VALUE:-$VERCEL_APEX_A}"
say "  Set www:            CNAME  ->  ${VERCEL_WWW_CNAME:-<from stage 2>}"
say ""
step "REMOVE the existing A records pointing @ and www at 89.31.143.90 —"
step "  that is the parking page, and it will otherwise keep answering."
step "Leave app.gut8erpro.de exactly as it is. It already points at Vercel"
step "  and serves the dashboard; touching it will break the live app."
warn "Do not delete MX or TXT records — those carry your email and domain"
warn "verification. Only the A/CNAME records for @ and www change."
say ""
note "Propagation is usually minutes, occasionally up to an hour. Vercel will"
note "issue the TLS certificate automatically once DNS resolves."
pause "DNS records saved at united-domains?"

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Google Cloud Console — verify the OAuth client"
say "Google sign-in goes through Supabase, not through the app directly."
say "So Google's redirect URI points at Supabase and does NOT change in this split."
say "This stage is a verification, not an edit — expect to change nothing."
open_url "https://console.cloud.google.com/apis/credentials"
step "Open the OAuth 2.0 Client ID used for Gut8erPRO sign-in."
step "Under 'Authorized redirect URIs', confirm this exact entry is present:"
say  "    ${SUPABASE_CALLBACK}"
step "If it is missing, add it and Save. If it is there, change nothing."
step "Leave any http://localhost:3000 entries in place for local development."
pause "Done in Google Console?"

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Apple Developer — verify Sign in with Apple"
say "Same story as Google: Apple returns to Supabase, not to the app."
open_url "https://developer.apple.com/account/resources/identifiers/list/serviceId"
step "Open the Services ID configured for Sign in with Apple → 'Configure'."
step "Under 'Return URLs', confirm this exact entry is present:"
say  "    ${SUPABASE_CALLBACK}"
step "Under 'Domains and Subdomains', confirm ${SUPABASE_REF}.supabase.co is listed."
warn "Do NOT add app.gut8erpro.de as a Return URL — Apple never redirects there."
pause "Done in Apple Developer?"

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Stripe — repoint the webhook endpoint"
say "This is the one external change the split genuinely requires."
open_url "https://dashboard.stripe.com/webhooks"
step "Open the existing Gut8erPRO webhook endpoint (or create one if absent)."
step "Set the endpoint URL to:"
say  "    ${APP_ORIGIN}/api/stripe/webhook"
step "Keep the same subscribed events; save the endpoint."
step "Click 'Reveal' under 'Signing secret' and compare it to the current value."
note "Editing an endpoint's URL usually keeps its signing secret; a NEW endpoint"
note "always has a new one. Only update Vercel if the value actually changed."
say ""
open_url "https://vercel.com/${TEAM}/${APP_PROJECT}/settings/environment-variables"
step "If the secret changed: set STRIPE_WEBHOOK_SECRET (Production), then redeploy."
warn "Paste it straight into Vercel — don't route the secret through this script."
SKIPPED+=("Confirm STRIPE_WEBHOOK_SECRET matches the live endpoint's signing secret")
pause "Webhook repointed?"

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Verify the cutover"
say "Six checks. Stop and report any that fail before calling the split done."
say ""
step "1. ${MARKETING_ORIGIN} serves the German landing page over HTTPS"
step "   (not the united-domains parking page, and no certificate warning)."
open_url "${MARKETING_ORIGIN}"
step "2. ${MARKETING_ORIGIN}/en/ serves English;"
step "   ${MARKETING_ORIGIN}/legal/impressum serves the Impressum."
step "3. www.gut8erpro.de redirects to the apex."
step "4. ${APP_ORIGIN} shows the dashboard when signed in, and redirects to"
step "   /login when signed out (try a private window)."
open_url "${APP_ORIGIN}"
step "5. OAuth: sign in with Google and with Apple; each lands back on ${APP_ORIGIN}/."
step "6. Password reset: request one and confirm the email link host is"
step "   app.gut8erpro.de. (Requires ticket 06 — Supabase Site URL — to be done.)"
say ""
step "Then in Stripe: 'Send test webhook' → expect a 2xx response."
open_url "https://dashboard.stripe.com/webhooks"
if confirm "Did every check above pass?"; then
  say "Cutover verified."
else
  SKIPPED+=("Re-run the failing verification checks from stage 7")
  warn "Note which check failed and hand that back to the agent."
fi
pause "Ready to finish?"

finish
